### ISSUE TITLE
Allowed type tag patterns and optional arguments

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#105]
I've noticed a few servers use the type tag pattern `['_', 'sometype']` with the absence of the argument indicating a query and the presence indicating a command.  I implemented this pattern for a few settings but with more parameters than one (for instance, `channel` and `value` where value is None or a boolean) and was surprised at this error:
`'' not allowed after first arg.`
Does this imply that a LabRAD setting is limited to at most one optional argument, which must be the first argument?  If so, why do so many @setting methods have arguments with default values?  For example, in DataVault,
```python
@setting(21, limit='w', startOver='b', returns='*2v')
    def get(self, c, limit=None, startOver=False):
```
yet it is impossible to call this setting without specifying `limit` and `startOver`.

**Comment by DanielSank** [comment]
+1 because I think this needs to be properly documented.

**Comment by maffoo** [comment]
There is a difference between explicitly providing a type like `['_', 'someType']` to the `@setting` decorator versus defining arguments with default values. Let me see if I can explain. In labrad as it currently stands, multiple arguments are acutally passed as a tuple, but tuple's cannot contain `None` as members. So, suppose you had three string arguments to a setting, the latter two of which have default values:
```python
@setting(1, a='s', b='s', c='s')
def get(self, ctx, a, b=None, c='test'):
    pass
```
The you can't actually pass `(ss_)` or `(s_s)` because those are not valid data, so it would not be correct to say that `b` or `c` accept `'_'` as input. However, because there are default values defined in python, the decorator will detect that and allow `(ss)` or just `s` as accepted types for the _entire setting_; when it gets one of these it unpacks them to the appropriate number of params and the rest get the python defaults.

So, if you have default values, don't try to add `'_'` as an accepted labrad type; the `@setting` decorator will generate accepted types with various numbers of trailing params omitted (while this would work for a single parameter, I'd suggest not doing it, just to keep things consistent). When you call a setting with default args, you can drop the last param, or both of the last two, or in general all of the last `k`, but you can't pick and choose like with regular python named args and default values.

(I should say, I've thought about relaxing this restriction on not allowing `None` inside a cluster, which would then make it possible to specify any subset of params with default values and make this whole issue go away. Scalabrad already allows this, but I haven't turned it on because we'd have to make corresponding modifications to pylabrad. Once we've excised delphi, this would be fairly straightforward and would make setting calls much more flexible.)

**Comment by DanielSank** [comment]
This should be a wiki page.

**Comment by maffoo** [comment]
added to wiki: https://github.com/labrad/pylabrad/wiki/Writing-Servers#parameters-with-default-values
