### ISSUE TITLE
1024 ns is greater than 1.024 us

### ISSUE THREAD

**Issue by JulianSKelly** [labrad/pylabrad#118]
```
In [112]: 1024*ns < 1.024*us
Out[112]: False

In [113]: 1024*ns > 1.024*us
Out[113]: True
```

**Comment by pomalley** [comment]
Floating point comparison?

**Comment by ejeffrey** [comment]
This is a floating point conversion issue. The offending code is this:

In [38]: 1e-6 / 1e-9
Out[38]: 999.9999999999999

I think this happened because of the unit conversion caching by @maffoo.
When I checkout tag 21762c (which used the Fraction class to keep track of
the powers) this behaves as expected.

Evan

**Comment by ejeffrey** [comment]
We need to merge #175 so we can see the performance impact of fixing this
