### ISSUE TITLE
labrad teams and permissions

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#123]
I would like to be involved in this organization, but it is not appropriate for me to be in the owners team.  For example I don't want direct write privileges to pylabrad.

I would like to try and contribute to the wiki, and possibly other future repositories.

Has anyone given thought to teams and permission for this organization?

**Comment by chrismacklin** [comment]
I am also interested in this.  I would love to be able to contribute to the wiki.  It would also be nice to be able to contribute to development without having to go through the external pull request process, but that's a minor issue.

**Comment by DanielSank** [comment]
This is a good issue to discuss sooner rather than later. As far as I see it, there are two possible workflows on github

Let me describe what I think is the most sensible work flow:

1. Each group using LabRAD (i.e. Irfan's group etc.) should fork the repos they care about.

1. Within that group, development happens however that group wants. I can offer some advice about this, but for now it doesn't matter. Somehow commits are added to the fork.

1. When a group thinks they have some useful code to contribute back to the main repo, they just submit a pull request. That PR will be reviewed by the owners of the LabRAD org (or maybe more specific teams within the org) and eventually accepted and merged.

@chrismacklin the pull request process is pretty important. We've found in our own group that insisting on careful reviews of *all* code changes has significantly improved reliability and quality of the code. We use a pull request and review system even within our own group. Nobody is allowed to merge anything into master without a review. I think this is important even for the wiki because one thing reviews really help with is clarity of documentation.

So, @jayich and @chrismacklin, can you guys fork the repos you're interested in for your respective groups? Once you do that, I recommend the following workflow, which is a compromise between efficiency and safety, within your group

1. Make an organization for your group.

1. Make teams for each repo you care about and add appropriate lab members to each team.

1. When a code change needs to happen, make an issue describing the intent and then make a branch with the same number as the issue. For example, if issue number 32 is "Add spin-echo experiment", then you'd make a branch called `32-spin-echo`. Someone develops the spin echo code in that branch.

1. When the code is ready, submit a PR for that branch within your group's fork. The PR is reviewed and improved.

1. Eventually the PR is ok'd and merged into master on your fork. We like to rebase our branches before merging to keep the history linear (i.e. no merge commits on master) but that's a matter of taste. I'd be happy to share our contributing instructions as a model if you'd like.

@maffoo @pomalley what do you guys think?

**Comment by chrismacklin** [comment]
@DanielSank I understand the need for code review; the PR process is slightly more involved from a fork, but as I said that's not a big issue.  The main issue that I see is that there is no way to submit PRs against the wiki - without being members of the organization, there is no way for us to contribute to the documentation.  One possible solution to this would be to move the wiki from the github repo to an external wiki service to enable separate edit privileges for the documentation.

**Comment by DanielSank** [comment]
@chrismacklin If you fork a repo doesn't its wiki come with it? The wiki is just a git repo after all. Can you give that a try?

**Comment by chrismacklin** [comment]
Github doesn't have a PR process for wiki pages; the workaround most people seem to do is to make changes on your forked version of the wiki, file an issue, and someone in the group must manually merge them.

**Comment by pomalley** [comment]
That's unfortunate. I think documentation is generally so low-priority in people's minds (including mine) that we should try to have as small of a barrier to documentation-writing as possible.

**Comment by DanielSank** [comment]
I totally agree with Peter. Adding to the wiki needs to be turbo easy. A pattern I'd like to encourage is that any and all questions about how LabRAD works should be answered by writing wiki pages, i.e. if someone posts an issue asking a question the response is a wiki page and a link in the issue tracker.

Anyway, how do we actually make this easy? The system described in @chrismacklin's link seems too manual to stick. I'm going to see if [this idea](http://stackoverflow.com/questions/6941688/how-to-integrate-a-github-wiki-into-the-main-project) will work for us.

**Comment by pomalley** [comment]
Another option is to just let contributors write straight to the wiki and require that the preface their edits with "The following is unreviewed", and then make an issue, and then the reviewer can remove that line after review. Kinda lame, but it's a relatively small barrier.

**Comment by DanielSank** [comment]
@pomalley is there a way to do this without giving everyone commit on the repo itself?

**Comment by chrismacklin** [comment]
@pomalley unfortunately it is not possible to grant write permissions only to the wiki without also allowing write access to the source repo.

**Comment by DanielSank** [comment]
Can we just make the wikis there own repos? That seems like a super easy solution? The only problem is that I'm not sure if they'll render nicely with all the little disbar navigation stuff etc.

**Comment by pomalley** [comment]
Well, there is something to be said for there being a "LabRAD wiki" so we don't have to be pedantic about what belongs in pylabrad vs. whatever (though I guess most things happen in pylabrad these days).

**Comment by DanielSank** [comment]
> Well, there is something to be said for there being a "LabRAD wiki"

Good point. Making each wiki for the repos their own repo works in N-1 cases though :-)

**Comment by DanielSank** [comment]
Er, well, I guess it doesn't really. I just made a new repo `pylabrad-wiki` and unfortunately it doesn't render with all the nice sidebars etc.

**Comment by chrismacklin** [comment]
It would be nice to bring all the documentation together under one LabRAD umbrella, with internal structure for language-specific interfaces.  Then specification-implementation cross-referencing could be done more easily; eg a page on labrad type tags in the general area, cross-referenced to a page on pylabrad/python type conversion rules in a pylabrad section.

**Comment by pomalley** [comment]
I agree with @chrismacklin. Why don't we use the [LabRAD repo](https://github.com/LabRAD/LabRAD) since that seems to be what it's for? I think having multiple wikis will just cause things to disperse unnecessarily.

**Comment by jayich** [comment]
Started this issue for the wiki:  https://github.com/labrad/pylabrad/issues/124

**Comment by DanielSank** [comment]
@chrismacklin @pomalley This doesn't seem to address the issue this thread was originally about, namely now contributions to the wiki should happen.

We seem to now be talking about two things:

1. How do we manage contributions to the wiki?

1. Should we have a wiki in each repository or just one global wiki?

I am in favor of one wiki per repository. I think if scalabrad, pylabrad, jlabrad, and whatever else all wind up under one umbrella it's going to be harder for people to understand what's going on. The LabRAD wiki should explain the protocol and system architecture. It should also probably have a link to a getting started tutorial in pylabrad. The pylabrad wiki should describe how pylabrad works, assuming the reader already understands LabRAD architecture.

**Comment by DanielSank** [comment]
@chrismacklin linking to github resources isn't particularly difficult. Can you explain what you mean by having one wiki making linking easier?

**Comment by chrismacklin** [comment]
@DanielSank Having all the documentation in one place would make it much more portable; if I wanted all of it in one place for easy reference, I could clone the entire wiki to a local repo and have everything.

**Comment by pomalley** [comment]
I too would prefer one wiki; I think it's simpler to put a header on a wiki page that says which API (or whatever) that page is for than to reference across wikis. But it's a minor thing in any event.

**Comment by DanielSank** [comment]
> But it's a minor thing in any event.

Perhaps but we should make a decision :-)

**Comment by pomalley** [comment]
OK, I decide that we should have one wiki. :-)

**Comment by DanielSank** [comment]
@pomalley How will the permissions work?

**Comment by pomalley** [comment]
The wiki goes in the LabRAD repo, and we all get permissions there. Or we just make a new repo with the wiki only and we all get permissions there. Right?

**Comment by jayich** [comment]
Is the idea that the pylabrad-wiki (if it is the solution) be linked to the wiki on this repository?

**Comment by DanielSank** [comment]
@jayich yeah that would make sense. Another thing that would really help is an autogenerated TOC.

**Comment by maffoo** [comment]
After discussing with @DanielSank, I think we're going to try the following for now: we'll use the regular github wikis for documentation. We've set the wikis to allow contributions only from people with commit access, but we've also added a `doc/wiki` tag so that people who have suggestions for documentation can just file an issue with that tag attached. No need for pull requests or reviews on wiki changes from contributors, but if it's a large change or you want feedback or you want someone else with expertise on a particular part of the code to weigh in before making the change or whatever, then contributors can also file documentation issues. We're also thinking it makes sense to keep the separate wikis, so the labrad/labrad repo will have general info while labrad/pylabrad and labrad/scalabrad wikis will have language-specific details. It's straightforward to make links between wikis (it's just the internet), so I don't anticipate this being a problem, but we can see how this works and revisit as needed.

@jayich, if this addresses your concern, let's close this. Anyone else have thoughts?

**Comment by DanielSank** [comment]
We should also make the various readme files advertise, in very large type, how to submit documentation. Something like this

### Documentation

If you are not a committer to this repo but you'd like to contribute to documentation, please file an issue and add the "doc/wiki" label. We really like it when people do this.

**Comment by maffoo** [comment]
good call, @DanielSank. Done.
