### ISSUE TITLE
Current labrad version is labrad.__version__ = '0.93.1'

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#129]
Is 0.93.1 the latest version?  I noticed 0.93.2 in this:

https://github.com/labrad/pylabrad/blob/1f40e27c06cf62fd1c73cb8f293572d6ba582761/CHANGES.txt

There have also been recent commits to master, possibly not relevant to version control?  Just wanted to make sure this is known.

**Comment by DanielSank** [comment]
I think we should get in the habit of tagging commits so there's some semblance of releases.

**Comment by chrismacklin** [comment]
The way to be serious about this is have a separate numbered release branch and periodically merge master (or develop or whatever) into it, creating a new numbered release.

**Comment by maffoo** [comment]
I think the thinking there was we started recording changes that would go into the next version (0.93.2), but we never actually bumped the version number and did a release.

Since then, we have not been keeping that CHANGES file up to date, and to be honest I'd prefer to just rely on the git commit history if possible because it's hard enough to write good commit messages, let alone keep track of changes in two places.

We do need to have better procedures around releasing, but have gotten out of that habit because in our lab we just run off of master and don't install packages. At this point I'd be inclined to bump to 0.94 when we cut a release from master because we've had some backwards-incompatible changes (e.g. some member renaming in units.py). Thoughts?

**Comment by jwenner** [comment]
Since pylabrad on pypi (https://pypi.python.org/pypi/pylabrad/0.94.0) has now been updated, can we close this?

**Comment by maffoo** [comment]
Closing as suggested by @jwenner. You'll note that there is no more `labrad.__version__`. Instead, the version information is created at build time and placed in the `labrad.version` module. The versions are based on git tags.
