### ISSUE TITLE
Was there an API change notification on the value attribute to base_value change?

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#131]
I missed this API change:

labrad.units.Value.value attribute is now gone, and I think it is replaced with labrad.units.Value.base_value.

It would be great if when public attributes are changed there was some type of notification, tag, or release note.  I tried searching issues and the repository, but nothing obvious came up.  I remember loosely following units discussions, but didn't appreciate there was going to be an API change.  Please point out if I am missing something obvious, or if the change was not considered part of the API.

Okay, looking over the public attributes of labrad.units.Value it looks like some attributes should have _'s in front of them.  Perhaps not?

**Comment by maffoo** [comment]
`base_value` is *not* the same as value, and yes, it should probably have a leading underscore because it is not meant to be part of the public api. For that matter, `value` was not meant to be part of the public api either, which is why it got renamed to `_value` at some point. The idea is that you want to be explicit whenever you extract a bare number from a quantity with units about which units you are using, and we overload the square bracket indexing notation for this:

```python
>>> from labrad.units import ms, s
>>> x = 1*ms
>>> x[ms]
1.0

>>> x[s]
0.001
```

Just to be clear, `base_value` is the value expressed in base units (which essentially the bare SI units with no prefixes like `m` or `G`):

```python
>>> x.unit
<Unit 'ms'>

>>> x.unit.base_unit
<Unit 's'>

>>> x[x.unit], x._value
(1.0, 1.0)

>>> x[x.unit.base_unit], x.base_value
(0.001, 0.001)
```

As to the question about our process for dealing with breaking changes, I think we need to do two things: we need a better-defined release process (see #129) so we can manage when breaking changes happen and bump the major or minor version numbers, depending on the size of the change. We also need to document what the actual api is, which is unfortunately somewhat tricky to do for python because the language is so flexible. But at least being careful about using leading underscores in names would help.

**Comment by jayich** [comment]
@maffoo, thank you for these clarifications, this helps a lot.  We are switching to the superior convention (x[s]) in places where it was not used.
