### ISSUE TITLE
Cannot connect to manager during initServer call

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#150]
I can guess why this doesn't work, but really I have no idea.  Here's a minimal example:
```python
from labrad.server import LabradServer
import labrad

class CxnLockupServer(LabradServer):
    name = "cxn failure"

    def initServer(self):
        print "Connecting..."
        cxn = labrad.connect()
        print "Connected."

__server__ = CxnLockupServer()

if __name__ == '__main__':
    from labrad import util
    util.runServer(__server__)
```
prints
```
2015-08-26 12:16:27-0700 [-] Log opened.
2015-08-26 12:16:27-0700 [-] Starting factory <__main__.CxnLockupServer instance at 0x10478a1b8>
2015-08-26 12:16:27-0700 [Uninitialized] connected to 127.0.0.1:7682
2015-08-26 12:16:27-0700 [ServerProtocol,client] cxn failure starting...
2015-08-26 12:16:27-0700 [ServerProtocol,client] Connecting...
```
then hangs so hard I have to kill the entire terminal session.  Why can't I get a manager connection at this point in server configuration?

**Comment by ejeffrey** [comment]
You shouldn't be calling connect() inside a server at all.  Once the
connection is up you should have a client connection that you can use to
make manager requests.

**Comment by maffoo** [comment]
@ejeffrey is correct. Inside a server `self.client` is a connection object that you can just use; no need to connect again. Note that it is asynchronous, returning twisted `Deferred`s instead of blocking until responses are available.

To explain a bit more about what's going happening, the code in `initServer` is running in the twisted reactor thread. This is asynchronous code, meaning that instead of blocking to wait for responses from network requests, you install a callback to be invoked when the response is available and then yield control back to the reactor so that it can run other tasks in the meantime (`Deferred` objects are used in twisted to manage the callbacks). `labrad.connect` on the other hand is synchronous, "blocking" code. It runs the twisted reactor in a background thread and then puts a synchronous interface on top, which blocks waiting for things to happen in the reactor. So, the call to `labrad.connect` blocks waiting for the twisted reactor to do some work, but you're calling it in the twisted reactor thread and hence preventing the reactor from getting any work done. Hence the deadlock. (This is leaving aside for now the additional problem that you can only run one copy of the twisted reactor, so trying to start up another one in a separate thread is going to fail.)

We should probably add a check in the `labrad.connect` code to fail quickly and loudly if it gets called from inside the twisted reactor thread, which would give an indication of the problem instead of just deadlocking.

Note also that if you need to establish a _separate_ connection to labard besides just reusing the server connection (for example, if you wanted to connect to a different labrad manager), you could use `labrad.connectAsync` instead of `labrad.connect`, e.g.:
```python
@inlineCallbacks
def initServer(self):
    asyncClient = yield labrad.connectAsync('other-host')
    # do something with asyncClient
```

For more on the asynchronous stuff, see the [wiki](https://github.com/labrad/pylabrad/wiki/Asynchronous-programming-HOWTO).

**Comment by maffoo** [comment]
erm, that wiki page I linked to doesn't really explain what I thought it explained (it doesn't say anything about real asynchronous clients, just the fact that you can say `wait=False` with a synchronous client to have multiple requests in flight at once. The actual asynchronous stuff needs to be added.

**Comment by chrismacklin** [comment]
Fabulous, thanks for the clarification.
