### ISSUE TITLE
Value comparisons for infinity have different behavior from dimensionless floats

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#158]
```python
>>> from labrad.units import s
>>> float('inf') == float('inf')
True
>>> float('inf')*s == float('inf')*s
False
```

This is due to the fact that \_\_cmp\_\_ for WithUnit is implemented as
```python
def __cmp__(self, other):
        '''
        This just returns the difference between self and other.
        We don't call cmp() on it to convert to +/-1 or 0 because
        that doesn't work on complex numbers, even if we only want
        to test for equality.
        '''
        return self._sum(other, 1, -1)
```
and inf - inf = nan

**Comment by DanielSank** [comment]
Oh boy. Units again.

**Comment by chrismacklin** [comment]
I'm firing up the boiler in the engine of the never-ending-special-casing express.  WOO-WOO. ;0

**Comment by ejeffrey** [comment]
Hmm... IIRC, WithUnit does comparison by converting to (a-b) ?= 0.
infinity - infinity == NaN.  I am not even sure that infinite units are
something we want to support, but if we do, they should work the same way
as floats.

**Comment by ejeffrey** [comment]
Of course, when I say infinity - infinity == NaN, what I really mean is
infinity - infinity -> NaN.  NaN doesn't equal itself :P

**Comment by chrismacklin** [comment]
Well, count me as one vote for the support of infinity with units.  For time, at least, it makes perfect sense.  "How long does this operation go on?  Forever."

**Comment by chrismacklin** [comment]
I also really don't understand the explanation in the docstring of that method.
```python
>>> complex(1.0,1.0) == complex(1.0,1.0)
True
>>> complex(1.0,0.0) == float(1.0)
True
```

**Comment by ejeffrey** [comment]
In older versions of python, comparison operators (<, <=, =, >=, >, !=)
were implemented in classes by implementing a single special method
__cmp__() that returns '-1' for less than, '0' for equal, and '1' for
greater than.  The results for the individual comparison operators were
based on the result of __cmp__.  This avoids having to separately write 6
methods.  Unfortunately it doesn't support the notion of partial ordering,
or allow equality / not-equal comparison for types like complex that do not
support ordering, but do support equality.  So that is deprecated in favor
of __lt__, __le__, and friends, but units is still based on __cmp__.  This
just needs to be converted to implement the 6 comparison operators
separately.

Evan
