### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by chrismacklin** [labrad/pylabrad#162]
Has anyone put any thought into porting pylabrad?  This is especially appealing with the introduction of standardized static type hints in 3.5.

**Comment by pomalley** [comment]
Last time I checked the issue with this was Twisted. Have they moved to Python 3 yet?

**Comment by chrismacklin** [comment]
Hmm, looks like their 2 to 3 port is only at ~50% by line coverage:
http://labs.twistedmatrix.com/2015/09/twisted-devlog-september-2015.html

I don't know enough about which features pylabrad uses to have any idea if the twisted services in use are among those which have been ported.

**Comment by joshmutus** [comment]
I thought python 3 had it's own asyncronous something something which could
effectively replace twisted.

**Comment by chrismacklin** [comment]
Simultaneously trying to both port the library to 3 and replace a core dependency sounds pretty painful to me...

**Comment by maffoo** [comment]
There's (still) no version of twisted for python 3, and I'm not holding my breath (it's a really slow-moving project and they seem to be more concerned about stability than anything else).

I did an experiment a while back to see what it would take to get things running on python 3 (see [this branch](https://github.com/labrad/pylabrad/tree/u/maffoo/python3)). The biggest issue I ran into was dealing with str/unicode/bytes because string literals produce unicode objects in python 3 but we have to send bytes over the wire. I got that to work for flattening, but unflattening is tricky because labrad doesn't have a distinction between text and bytes, so we can't know the right thing to unflatten to and don't have a good way to specify. I think creating a separate labrad type for (unicode) text would help with this, but that would be a big change in the python 2 code as well.

There are some other issues as well, like how to maintain a shared codebase that works for python 2 and 3 (so we don't have to maintain a fork). I've seen two main approaches; one is to basically code to a lowest-common denominator of functionality between the two (in effect, make python 3 work like python 2), while the other is to use helper libs to add new features to python 2 (make python 2 work like python 3).

**Comment by ejeffrey** [comment]
BTW, I am fine with forking pylabrad and having a python 3 version that
supports new features and a python 2 version that gets bugfixes only.
Obviously we would want to strive for as much compatibility as possible,
but if major parts of the backend need to be rewritten to support a new IO
system with no backport available, I would rather have separate branches
than add an extra layer of abstraction and try to keep both in the same
codebase.

**Comment by ejeffrey** [comment]
I should add: I think we need to solve the unicode issue in the existing
python 2 codebase before we can really contemplate moving to python 3.
That is definitely the trickier part.  Re-implementing the IO stack is a
fair bit of work, but it is somewhat self contained.  As long as we are
just switching to another single threaded async io platform, I don't think
it is too onerous.

Matthew and I have talked about the string/unicode thing a few times, maybe
anyone else can chime in with their opinions: the idea is to change the
labrad 's' datatype to mean unicode (with the wire format being UTF-8
encoded), and to make a new type to represent 'bytes'.  This could be
either a dedicated type, or this could go along with adding new fixed-width
numeric types (i8, i16, i32, i64, and the equivalent w types), in which
case "byte string' would just be *w8.

The alternative is to make a new typetag 'u' for unicode, and keep 's' as a
byte string.  This would technically be more backwards compatible, but I
would estimate that 95% of our existing use of 's' should, in fact, be
unicode, so I think that the former option is actually easier to implement.

Evan

**Comment by strj** [comment]
My drive-by $0.02 is that having encoded string and bytes types is A Good Thing that will make things a lot clearer in general and could pave the way to moving to better defined apis between servers with e.g. [proto3](https://developers.google.com/protocol-buffers/docs/proto3?hl=en#scalar).

**Comment by pomalley** [comment]
re: string vs unicode, I think there is a non-negligible amount of 's' out
there that is actually bytes in the various device servers (i.e.
downloading data from a scope, etc). Maybe it's worth going through and
fixing those manually but I'd also bet that other groups also use 's' for
byte data as well.

**Comment by maffoo** [comment]
My thought is to introduce a byte type (let's say we call it `w8`) so that byte strings would just be `*w8`. Then, as @pomalley suggests the existing places where we use `s` for binary data could be converted to `*w8` and once that is done we can just silently redefine `s` to assume utf-8 encoding for text data. We'd still need a better mechanism to specify what python types to use when unflattening since `*w8` could be converted to a numpy array or bytearray, for example, but I think this would be a good thing for pylabrad anyway.

**Comment by ejeffrey** [comment]
Most of our instruments are used in ASCII mode, which would be compatible
with unicode.  There are definitely a few that use binary data for the
"download waveform" command, and the FPGA and direct ethernet servers use
it extensively for transferring packet data.  However, I think this is
still a relatively small number of settings.

Note that plain ASCII is a valid encoding of unicode, so device strings
that need to pass plain ASCII would use unicode type tags, and then when
you are actually going to write the data, you would have to do
str.encode('ASCII') which will fail if there are code points outside the
valid range.

**Comment by jayich** [comment]
@maffoo I think this issue can be closed.
