### ISSUE TITLE
docstring example(s) on the wiki

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#195]
Including example docstrings in the Writing Servers (https://github.com/labrad/pylabrad/wiki/Writing-Servers) on the wiki would be helpful.  I would put an example in this issue, but I keep getting my server docstrings mixed up...

label: doc/wiki

**Comment by maffoo** [comment]
What kinds of things do you want to see documented in an example? There are lots of short setting docstrings there; are you looking for example of how to format them? Or maybe an example of a docstring for the whole server? I hesitate to be too prescriptive because the basic idea is just to write docstrings like you normally would for any public python method or class, just remembering that the docstrings will be visible not only to readers of the code, but also to remote labrad clients.

**Comment by jayich** [comment]
Ah, thank you @maffoo & @ejeffrey.  This issue is resolved for me.
