### ISSUE TITLE
formatting numbers with units

### ISSUE THREAD

**Issue by roboguy222** [labrad/pylabrad#219]
I am not sure if this is expected behavior or not, but I thought I would note it here in case it is not.  One can format a float in python using `"{0.3f}".format(x)`, to display a float x with 3 decimal places, for example.  This throws an error in the newer versions of pylabrad, but not in the old ones, if x has labrad units attached.  Just FYI.

**Comment by roboguy222** [comment]
Relatedly, functions like numpy.nanmin can no longer be used with an array of numbers with units.

**Comment by ejeffrey** [comment]
Hi Chris,

The old version of pylabrad allowed implicitly stripping the units off.  We
found this to be a problem because, for example if x was "3 microseconds",
your example would print 3.000, but if it was 3000 nanoseconds, it would
print 3000.000.  This could easily happen if the value is passed in from
out outside function or entered by the user.

So the currently recommended way to do this is either to explicitly
evaluate x with x['ns'] or similar, or to just use the stringification
operator str(x) which will print the value including its units, but does
not let you specify the precision.

We should look into making formatters that allow you to print a value with
specified precision.  I don't know how to do that, but it is probably
possible.

**Comment by maffoo** [comment]
You _can_ format values if they are dimensionless:
```python
>>> x = 1*labrad.units.Unit('')
1.0
>>> type(x)
labrad.units.DimensionlessFloat
>>> '{:0.2f}'.format(x)
'1.00'
```

But as @ejeffrey mentioned, we've found it's a very bad idea in general to allow numbers with units to be transparently treated like floats, so we've changed those behaviors.

It looks like formatting can be customized using the [`__format__` method](https://docs.python.org/3.1/reference/datamodel.html#object.__format__) in python3, but I don't see any equivalent in python2.

**Comment by ejeffrey** [comment]
With regards to numpy, most operations will only work on value arrays that
are dimensionless, again to avoid ambiguous results, and implicit loss of
the unit information.

We could implement some of these functions as ValueArray class methods, but
then you have to use a separate syntax from normal numpy behavior.  numpy
1.11 is (hopefully) going to allow hooking into the ufunc mechanism so that
we can implement the numpy functions that make sense without having to use
different syntax, and raise exceptions for the ones that don't.  It is in
beta right now, and I am planning on testing it out in the near future.

nanmin and similar we intend to implement.  Anything that would require
discarding or ignoring the unit data won't be implemented, nor will
anything whose result would be dramatically different if the input has the
same value but different units (for instance, np.ceil()).

Evan

**Comment by roboguy222** [comment]
OK, just wanted to make sure it was intended.  I looked for the numpy ufunc thing, but as you said, it doesn't exist yet.
