### ISSUE TITLE
LazyList does not work with python list arguments

### ISSUE THREAD

**Issue by creilly** [labrad/pylabrad#227]
if we get a list value from, say, a registry call:
`values = yield reg.get('key')`
and then pass the list to a function as a list argument:
`foo(*values)`
then `foo` will interpret `values` as an empty list:
```
def foo(*values):
   print values # will print (), the empty tuple
```
casting `values` as a list fixes the problem, but I thought I should point this out since this is surprising behavior.

**Comment by ejeffrey** [comment]
Hi, thanks for reporting this.

Sadly I think this is unavoidable / expected behavior.  List and tuples are
special-cased by the python interpreter for things like argument
packing/unpacking, so we don't get a chance to do the lazy unpacking here.
The right solution for this is to make LazyList *not* subclass list, or get
rid of it altogether.

What we would like to have is to allow you to specifically say when you
want data to stay flattened, for instance as part of the @setting decorator
or as a flag when you make a remote call.  That would allow you to do the
optimization done in lazylist without the weird corner cases that it
causes, and also to be sure that you weren't unintentionally unflattening a
lazylist which can happen pretty easily.

On Sun, Mar 6, 2016 at 1:19 PM, Christopher Reilly <notifications@github.com
