### ISSUE TITLE
wiki requirements update

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#237]
I noticed after I figured out that I was missing futures that the wiki also needs to be udpated with this requirement.  requirements.txt was happily up-to-date and that is the first place I looked before perusing the wiki.

Feel free to close this issue whenever.

**Comment by jwenner** [comment]
@ejeffrey or @maffoo, I'd like to update the wiki as per the request above. Could I get a review on the following (since I don't know how to do PRs for the wiki)?

# Current:
## Required Packages

To get started with pylabrad, you'll first need to install some software:

1. **Python** version 2.7 or greater (Stay tuned for Python 3.x support). Python is, in our opinion, one of the best programming languages out there. It's easy to learn and easy to use, and helps you get more done faster.
1. **Twisted** version 2.5 or greater. Download it [here](https://twistedmatrix.com/trac/). Twisted is a networking framework for python that we use to handle all the low-level networking stuff for pylabrad.
1. **pylabrad**. Install from source, or use pip to get it from PyPI.


# Update:
## Required Packages

To get started with pylabrad, you'll first need to install some software. The most current list (with versions) can be found in requirements.txt.

1. **Python** version 2.7.x (Stay tuned for Python 3.x support). Python is, in our opinion, one of the best programming languages out there. It's easy to learn and easy to use, and helps you get more done faster.
1. **Twisted** version 14.0 or greater. Download it [here](https://twistedmatrix.com/trac/). Twisted is a networking framework for python that we use to handle all the low-level networking stuff for pylabrad.
1. **pylabrad**. Use pip to get it from PyPI along with all the other dependencies. If instead installing from the source, make sure to check the list of other dependencies in requirements.txt.

**Comment by ejeffrey** [comment]
LGTM

**Comment by jwenner** [comment]
The wiki has now been updated as above. Note that I did not list all the requirements to avoid duplication (as requirements change) but we now explicitly reference the requirements.txt file. So @jayich, fine to close?

**Comment by jayich** [comment]
I agree that is best to not list all the requirements in the wiki.  Everything looks good to me.  Thanks again @jwenner .
