### ISSUE TITLE
PR #215 causes import error

### ISSUE THREAD

**Issue by DanielSank** [labrad/pylabrad#248]
```python
/home/daniel/src/pylabrad/labrad/backend.py in <module>()
     13 import Queue
     14 
---> 15 from concurrent.futures import Future
     16 
     17 from labrad import constants as C, support

ImportError: No module named concurrent.futures
```

As far as I can tell, `concurrent` is both a module in pylabrad *and* a python package, which is confusing. What are we supposed to do to make this import work?

**Comment by jwenner** [comment]
As in #228, run either `pip install futures` or `pip install pylabrad`.

**Comment by DanielSank** [comment]
I now see that `futures` was added to `requirements.txt`. This is really confusing that a package called `futures` has a module called `concurrent`, which we import in our own `concurrent.py` as `from concurrent.futures import Future`, so that elsewhere in the code the line

`import concurrent.Future`

is important *that*.

**Comment by maffoo** [comment]
@DanielSank, this is undoubtedly confusing. This sort of thing is one reason why we should always do `from __future__ import absolute_import`; then `import concurrent.Future` from a sibling module inside `labrad` is not a thing because you would always refer to `labrad.concurrent` while `concurrent` refers to the package from the futures dependency.

Additionally, I think it's an antipattern to import a symbol like `Future` from `labrad.concurrent`; that module imports `Future` to _use_ it, not to re-export it as part of its module interface. I think it's best to import things from the original source, rather than reexport them so they can be imported from multiple locations. Unfortunately, like so many other things, python doesn't actually provide a way to enforce this, as far as I know. If module `foo` imports a name `bar`, then other people can import `bar` from `foo`, whether or not that is what the author of `foo` intended. _C'est la vie_.

**Comment by ejeffrey** [comment]
I don't this it is automatically bad, particularly with the Future
example.  In this case there are multiple versions of Future that present
the same (or similar :( ) APIs, but are designed to be used with different
backends.  There is not only our old Future backport, but the python
concurrent.futures Future is different from the asyncio Future, the latter
having the machinery to be fired by the asyncio event loop.  By using an
import path for Future within the labrad package, we can make sure to get
the right one, which is very likely to change in the future.

I think the real problem here is the relative import.  It would be nice to
go through and find and kill any relative imports and convert the whole
code base to use from __future__ import absolute_import

**Comment by maffoo** [comment]
It's true that you might want to reexport in some cases, my point is that python doesn't provide a way _not_ to reexport a name, even though that's often what you want (you want to hide your implementation from users).

In the particular case you mention of `asyncio.Future` versus `concurrent.futures.Future`, they're not really interchangeable. The former is meant to be used inside an event loop thread, while the latter is for communicating an asynchronous result across threads (e.g. from the network code in an event loop thread out to a synchronous thread like an ipython session). It's another example of the fact that synchronous and asynchronous code (even coroutine-based asynchronous code) just don't mix well.

**Comment by DanielSank** [comment]
@maffoo for some reason, standing here right now, my brain cannot handle thinking about how imports work. Interestingly, this seems to be a common problem with my brain.
