### ISSUE TITLE
TLS and connecting to delphi managers from other computers

### ISSUE THREAD

**Issue by aransfor** [labrad/pylabrad#251]
since upgrading to pylabrad 0.95.3, a client we use that connects to a delphi manager on a different computer now requests a password even thought we have LABRADPASSWORD=password set. the warning given is:

STARTTLS failed; will retry without encryption in case we are connecting to a legacy manager.
Connected without encryption.

Is the delphi manager not compatible with 0.95.3 in regards to this environment variable when accessed from a foreign host?

**Comment by maffoo** [comment]
We changed the way password handling works slightly, so that now the LABRADPASSWORD environment variable will only be used when connecting to a manager on the default host (given in the LABRADHOST environment variable). If you connect to a different host, it will ask for a password, even if the env variable is set; passwords are cached per host, so you will only be asked once in a given interpreter session or program run. We probably need to figure ut a way to configure passwords for multiple manager hosts, probably in a config file somewhere, so the environment variables don't proliferate out of control.

The warning you're seeing about falling back to an unencrypted connection is because the old delphi manager does not support TLS. I would _highly_ recommend updating to scalabrad and using secure connections, but if that is not an option you can set things up to just connect without encryption and not see this warning. You can pass `tls_mode='off'` to `labrad.connect` when you establish a connection, or set the environment variable `LABRAD_TLS=off` to make this the default.

**Comment by jayich** [comment]
@maffoo , thank you, this is all good to know.  We are working on upgrading to scalabrad (https://github.com/labrad/scalabrad-web/issues/178)

I don't understand environment variables, but it might be possible to have one environment variable LABRADCONFIG that points to a local file where all the configuration information can be stored as a list of variables.  On Windows this would have the benefit of not needing to restart your computer after changing a variable in the config file.

**Comment by aransfor** [comment]
@maffoo We can upgrade, I did not know if scalabrad was a side project or if most of you had switched. Is the delphi manager not going to be upgraded anymore?

**Comment by ejeffrey** [comment]
Yes, scalabrad is now considered the mainstream choice for new deployment.
The delphi manager will still be available indefinitely, but is not going
to be updated any more.  So far the only real difference is TLS support,
but we do plan on adding protocol features that will not be supported in
delphi, such as unicode support.

You will want to check out the scalabrad-web package which provides a web
interface to the manager that has similar capability to the delphi
manager's GUI, plus a registry editor.

Note that there is an updated version of the Delphi registry editor that is
required to be used with the scalabrad manager.  The old version won't work.

**Comment by maffoo** [comment]
@aransfor, scalabrad is the way forward :-) We've switched entirely and seen substantial performance benefits, though the big advantage is that it's cross-platform so we're no longer tied to windows (or wine). Also, it's much easier to set up and maintain the dev environment, so that's where all new development is happening.

@jayich, I think it's worth exploring a config file option, we just have to figure out a good way to do this. It can get complicated with system configs and per-user overrides and things like that. Then we would also need a config file format and parsers for that. And it has to work cross-platform ("standard" paths for configs are different on windows and *nix). Environment vars are a simple mechanism, which is why I've tried to stick with that.

As for the question about needing to restart your machine when you change env vars, I think that should not be necessary. At most, you might have to start a new shell, but even that is not needed in some cases (for example, I think windows sends out a system-wide notification when system-level environment variables are changed, so running shells can even pick up the changes without needing a restart. But I could be wrong about this, it's been a while since I tried it out).

**Comment by aransfor** [comment]
where is the location of this new registry editor?

**Comment by jwenner** [comment]
When you log in to the `scalabrad-web` website (which requires Chrome), there is a menu icon in the upper-right where you can select the manager list (showing all connections to the manager), the list of servers for a node (where you can start/stop servers), a registry editor, and a grapher.

**Comment by aransfor** [comment]
OK, were off to the races, pretty straightforward switch. Thanks for the help

**Comment by maffoo** [comment]
closing for now. @aransfor, feel free to reopen or file a new issue if you have further questions.
