### ISSUE TITLE
registry.sqlite and git

### ISSUE THREAD

**Issue by jayich** [labrad/pylabrad#259]
Is it possible to track registry.sqlite changes with git?  We can make commits, etc., but we can't see what keys/values are changed.

**Comment by DanielSank** [comment]
@maffoo pointed out a while back that there's no real reason to use any particular format for the registry. We could use text files and stuff them all into a git repo, and we'd only have to write a little shim to interface it with the rest of LabRAD.

You could put an sqlite file in version control but since it's a binary format the diffs won't be particularly helpful.

**Comment by jayich** [comment]
I noticed the binary diffs weren't too illuminating.

So I could revert to the old plain text file format and do some conversion to sqlite?  That seems fairly reasonable.  If anyone has implemented this and has an example that would be helpful.

**Comment by DanielSank** [comment]
I wouldn't bother converting back and forth. Probably easier to just write a new interface lib so that the registry can read your favorite text format and then use that. There are a million and one "standard" text formats with nice I/O libs.

**Comment by ejeffrey** [comment]
I am pretty sure the manager already has at least one text backend, it has
one that is compatible with the old delphi manager.  This is somewhat
discouraged, as that format has known problems (some data is not round-trip
safe), but it works as well or better than it did with the delphi manager.
There is a command line argument to specify the format.  We also have a
conversion tool, although I don't know where it is.  I think there is also
an option where each key is in its own file, but the contents are just
binary data.  This would probably work well enough in version control as
you would see which keys were changed.

I thought about doing this a long time ago, but decided it would be hard to
make useful for our workflow.  What we can do instead is to use a feature
of our datataking script that takes a snapshot of the relevant registry and
adds it as "parameters" to the dataset.  Then we have a script that can
pull those keys from a dataset and restore them into a registry folder.

**Comment by DanielSank** [comment]
Where @ejeffrey said "What we can do" he actually describes something that we in fact *do*.

**Comment by ejeffrey** [comment]
Yes, that is what I meant.

**Comment by jayich** [comment]
Thank you for the info Evan.  Some combination of my Registry and git usage is causing problems with our Registry.

@ejeffrey , regarding round-trip safe, do some data types not get transferred properly?  I am tempted to try the text backend, but if you guys are moving away from that and to sqlite I feel like it is probably best to figure out sqlite.

**Comment by maffoo** [comment]
The registry configuration for the scala manager is documented in the command line interface, so you can see it by running the manager with the `--help` option (or look at [the code](https://github.com/labrad/scalabrad/blob/master/src/main/scala/org/labrad/manager/Manager.scala#L361)). Basically, you can specify a `file://` url that points to a file to store everything in a single sqlite file, or point it to a directory to store one key per file, with an additional `format` option to specify the delphi format compatible with the old delphi manager, or a binary format. The migration tool is called `labrad-migrate-registry` and is included with the packaged version of the manager; you can run it with `--help` to get info on it as well. It lets you migrate between the various formats, so you can try out different options if you like.

We've mostly been using the binary backend with one key per file. Turns out file systems are pretty fast, so this works well for us, while the performance of sqlite has not been great on some systems. The main advantage of the sqlite backend is that everything is in one file, so backups are easy, but that's not always the most important consideration. The text backend is mostly just for backwards compatibility. We fixed a number of bugs that existed in the old delphi manager, but still the text representation of labrad data is not full fidelity so you have to be a bit careful. For example, suppose you store an empty list of strings (`*s`) in the registry. The text representation of this is just `[]`, which has no information about the element type. When you get the data back, it will have a type of `*_`, which is a special-case list type for empty lists which we invented for this very purpose. In many cases you may not care about losing the list type info (in python one certainly doesn't care), but this gives maybe a flavor of the problems that can happen with converting to and from a text representation. You might also have floating point rounding issues, etc., etc. The binary backend stores labrad data exactly as it is encoded when sent over the wire, so it is by definition full fidelity, not to mention faster because we don't have to convert to/from the text representation.

**Comment by jayich** [comment]
@maffoo , thank you, that clarifies a lot.  I roughly found the source of our problems - stemming from a server that accesses the registry and associated *.pyc files.  I'm working on a fix.   @gregllong was able to successful migrate our registry a couple of weeks ago.  I am pretty sure we will stick with sqlite. 

I feel like my original question has been answered.
