### ISSUE TITLE
0-dimensional numpy arrays flattened to invalid data

### ISSUE THREAD

**Issue by maffoo** [labrad/pylabrad#260]
Numpy allows 0-dimensional arrays, but they are not flattened properly by pylabrad:
```python
In [1]: import labrad

In [2]: import numpy as np

In [3]: labrad.types.flatten(np.array([5]))
Out[3]: FlatDataBase(bytes='\x00\x00\x00\x01\x00\x00\x00\x05', tag=LRList(LRInt(), depth=1), endianness='>')

In [4]: labrad.types.flatten(np.array(5))
Out[4]: FlatDataBase(bytes='\x00\x00\x00\x05', tag=LRList(LRInt(), depth=0), endianness='>')
# this is not valid labrad data!!
```
It would be possible to add 0-dimensional array support to labrad and encode this as `*0i`, but I think that's maybe not the best course of action. One problem would be what is the text representation of a 0-d array (for example, in the registry editor)?

So, either we change this to (1) encode 0-d arrays as just scalars (e.g., just `i` instead of `*0i` in the example above), or (2) we fail on 0-d arrays and require the user to convert to a scalar. The disadvantage of (1) is that 0-d arrays will not be preserved when roundtripping through labrad (you put in a 0-d array and get back a scalar); I'm not sure whether all functions that expect 0-d arrays can deal with scalars, though I imagine the reverse works fine. The advantage of (2) is that the pylabrad changes are simple (just add a better error message instead of producing invalid encoded data) and we keep the data round-trippable, but the disadvantage is that users have to know not to try to send 0-d arrays.

**Comment by ejeffrey** [comment]
FWIW, numpy frequently automatically converts 0-d arrays to scalars.

For sure some code that expects to work on arrays will fail on scalars,
especially if they are straight python floats (rather than np.float64 which
implements the array API).  This is especially true if you try to use array
methods/attributes rather than the function versions in the numpy
namespace.  Well behaved array code _should_ use one of the utility
functions for coercing input to an array, such as np.asanyarray or
np.atleast_1d, but obviously that isn't universal.

I think any context where you could supply a list and have it auto-convert
to array will also handle a scalar.

I am definitely not wild about supporting 0-d arrays.  They are a mass of
special cases that make sense in a numerical computation library, but not
really for cross platform RPC.

Sorry, none of that is an answer.

**Comment by DanielSank** [comment]
@maffoo how did this come up?

**Comment by maffoo** [comment]
> Sorry, none of that is an answer.

LOL :) Do you have any feelings about (1) vs (2) in the issue description? Basically, should be flexible in what we accept (but then not preserve input data with full fidelity) or strict in what we accept (but then maintain fidelity because we reject 0-d arrays that can't be represented in labrad). I'm leaning toward (2), but only slightly.

@DanielSank, martinisgroup/pyle#1277

**Comment by DanielSank** [comment]
I'd go with option 2.

**Comment by DanielSank** [comment]
Particularly because it leaves option 1 available in the future if we decide we need it for some good reason.

**Comment by ejeffrey** [comment]
I agree with Dan.  Just reject it with a clear errors message.  If someone
comes up with a legit use case, we can do the auto-convert.  I don't have
any specific problem with auto-converting to scalars, but I don't really
think it should come up very often.  I expect that trying to flatten a 0-d
array usually indicates an error.
