### ISSUE TITLE
request detected as a string and not as a labrad.backbend.Future

### ISSUE THREAD

**Issue by ckometter** [labrad/pylabrad#263]
Hi,
I've been trying to do a simple blocking call but it detects my request as a string and not as labrad.backbend.Future
```
resp=dac_adc.buffer_ramp('01','1','-10,-10','10,10',1000,30000).future()
resp=resp.result()
```

I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\Laughlin\Documents\labrad test\test.py", line 13, in <module>
    resp=dac_adc.buffer_ramp('01','1','-10,-10','10,10',1000,30000).future()
AttributeError: 'str' object has no attribute 'future'
```
Thanks

**Comment by DanielSank** [comment]
I think I know what's wrong, but could you please include all of the code? It's not clear from what's posted whether you're showing client or server code.

In a client, the relevant code is [here](https://github.com/labrad/pylabrad/blob/master/labrad/client.py#L61), which I paste for convenience:

```python
def __call__(self, *args, **kw):
    wait = kw.pop('wait', True)
    if not wait:
        warnings.warn("Calling settings with wait=False is deprecated. "
                      "Use setting.future(...) instead.")
    f = self.future(*args, **kw)
    return f.result() if wait else f
```

If we set `wait=False` then we get the future back. However, as you can see, this is depreicated. If you look right underneath the code I linked at the `future` method you'll see the new interface.

**Comment by maffoo** [comment]
@DanielSank is correct @ckometter; the old way of making an asynchronous request was to pass a keyword arg `wait=False` but we realized it's a bad idea to change the return type of a function based on input parameters (that sort of thing makes it really hard to reason about types statically; IDEs hate it almost as much as humans). So, you need to call the `future` method on the setting, instead of the `__call__` method, which is what happens when you just stick parens on the setting. To be clear:
```python
resp = dac_adc.buffer_ramp(...)
```
is the same thing as
```python
resp = dac_adc.buffer_ramp.__call__(...)
```
and to make this asynchronous you should do
```python
resp = dac_adc.buffer_ramp.future(...)
```

**Comment by ckometter** [comment]
Thanks a lot. It worked.
