### ISSUE TITLE
Same server running on multiple nodes

### ISSUE THREAD

**Issue by edowd** [labrad/pylabrad#287]
Hi -- I have a scalabrad manager running on one computer and nodes running from the same computer and another computer. But I can't figure out how to have, for example, the same server running on each of the nodes simultaneously. I think it has to do with the instancename setting in the node header, but as soon as I add an instancename, the server doesn't start at all on either node. I am also confused about global vs local servers -- all my servers are registered as global. Is this a parameter you set somewhere when you write the server, or do you tell the node to see servers as global or local? Any clarification is much appreciated! Thanks.

**Comment by ejeffrey** [comment]
Yes, you are right about instancename.

Basically, "name" is the name that shows up in the browser.  "instancename"
is the name that the node will expect the server to show up as on the
manager, which must be unique on the manager.  The tricky part is that the
node header does not control the behavior of the server -- which must
register with the same name as listed in the instancename.  If these don't
match, then the node will never detect that the server has started up
because it will be looking for the wrong name.  If you go down to the
"class" statement for the server you are interested and change the "name =
fooserver" class attribute, then everything should work.

The way we typically make servers differentiated on a per-node basis is to
use %LABRADNODE% in the instance name, which will get interpolated with the
node name.  An easy example of this is in the serial server:

https://github.com/martinisgroup/servers/blob/master/serial_server.py

See lines 24 and 69.

local servers are just servers that have %LABRADNODE% in their instance
name.  The idea is, those are servers we expect to run on multiple nodes
because they talk to some hardware connected to those nodes (like a serial
port or GPIB interface).

**Comment by edowd** [comment]
Great, thanks!
