### ISSUE TITLE
Unit implementation is overly complex and brittle

### ISSUE THREAD

**Issue by maffoo** [labrad/pylabrad#76]
There are various problems here, but in particular we've recently found that unit computations are expensive and these things are hard to fix because the implementation is fairly obscure. Improved test coverage would also be good, both to better document the api and to catch regressions while refactoring.

**Comment by DanielSank** [comment]
We could also just rewrite the module to be less obscure...

**Comment by joshmutus** [comment]
What is it about units that's so bad? Presumably converting between units
is just a matter of multiplying by constants which should be really easy.
Is keeping track of the different kinds of units the problem? Could use
enforce just a smaller subset of units that could be used?

**Comment by pomalley** [comment]
> We could also just rewrite the module to be less obscure. There's pint and my own crummy attempt.

While we may want to do this eventually, there are going to be so many little gotchas that I'd personally much prefer that it happen after the jump table stuff is merged in--only one big rewrite at a time!

**Comment by DanielSank** [comment]
@joshmutus all I can say is that having tried to implement my own units library, I find that it's not completely trivial :-)

**Comment by joshmutus** [comment]
@DanielSank I believe you, I've never tried it myself so I don't understand where the complexity comes in? As a thought experiment: restricting myself to lengths, and enforce a rule that I have to use metric, then all I have have to worry about are the relationships between SI prefixes. Are there some tradeoffs that can be made to simplify things?

**Comment by ejeffrey** [comment]
The complexity is mostly of the death by 1000 needles variety.  One thing
is that we allow a number of different ways to create a new things with
units: you can explicitly construct it, you can multiply a float by a Unit
object, or by a Value object.  We want to support real numbers, complex
numbers, and numeric arrays with units, and we want all the standard
arithmetic operations to work they way you expect.  Just getting
multiplication to work as expected for every combination of (Value, Unit,
Complex, float, complex, np.ndarray, ValueArray(real), ValueArray(complex))
requires handling a lot of cases.  There are also some design choices we
made that are convenient for various reasons, but make the implementation
more complex.  We store values in the units you specify, rather than
converting to SI base units.  That means 4*ns will be stored as the number
4, and a unit object with a prefix of 10^-9.  But when we do comparisons we
have to convert to the equivalent units.  We even keep multiple equivalent
units distinct, so a Newton*meter and a Joule are different unit objects,
and they print the name of the unit you used, but they compare the same,
and you can still add them together correctly.  I made a substantial effort
to use exact math when possible, which added further complication.  That
means that the prefixes (like 10^-9) are stored as "1/1000000000" not
"0.000000001".  The reason for this is that you want expressions like "1*ns
* 1 * GHz" to yield 1.0 and not 1.0000000000004 or something like that
which might happen if you just converted to base units for arithmetic. This
is arguably not a good idea (code that assumes identities like that are
probably broken), but it makes stuff work particularly when dealing with
DAC samples that must be an exact multiple of 4 ns.

None of these issues is terribly complicated by themselves, but units.py is
what happens when you start off with a simple piece of code that works 95%
of the time, and then you fix 100 corner cases.

Evan

**Comment by joshmutus** [comment]
I see, thanks for explaining that.

On Tue, Mar 17, 2015 at 11:12 PM, ejeffrey <notifications@github.com> wrote:

> The complexity is mostly of the death by 1000 needles variety. One thing
> is that we allow a number of different ways to create a new things with
> units: you can explicitly construct it, you can multiply a float by a Unit
> object, or by a Value object. We want to support real numbers, complex
> numbers, and numeric arrays with units, and we want all the standard
> arithmetic operations to work they way you expect. Just getting
> multiplication to work as expected for every combination of (Value, Unit,
> Complex, float, complex, np.ndarray, ValueArray(real), ValueArray(complex))
> requires handling a lot of cases. There are also some design choices we
> made that are convenient for various reasons, but make the implementation
> more complex. We store values in the units you specify, rather than
> converting to SI base units. That means 4*ns will be stored as the number
> 4, and a unit object with a prefix of 10^-9. But when we do comparisons we
> have to convert to the equivalent units. We even keep multiple equivalent
> units distinct, so a Newton*meter and a Joule are different unit objects,
> and they print the name of the unit you used, but they compare the same,
> and you can still add them together correctly. I made a substantial effort
> to use exact math when possible, which added further complication. That
> means that the prefixes (like 10^-9) are stored as "1/1000000000" not
> "0.000000001". The reason for this is that you want expressions like "1*ns
> * 1 * GHz" to yield 1.0 and not 1.0000000000004 or something like that
> which might happen if you just converted to base units for arithmetic. This
> is arguably not a good idea (code that assumes identities like that are
> probably broken), but it makes stuff work particularly when dealing with
> DAC samples that must be an exact multiple of 4 ns.
>
> None of these issues is terribly complicated by themselves, but units.py is
> what happens when you start off with a simple piece of code that works 95%
> of the time, and then you fix 100 corner cases.
>
> Evan
>
>
>
> On Tue, Mar 17, 2015 at 10:32 PM, joshmutus <notifications@github.com>
> wrote:
>
> > @DanielSank <https://github.com/DanielSank> I believe you, I've never
> > tried it myself so I don't understand where the complexity comes in? As a
> > thought experiment: restricting myself to lengths, and enforce a rule
> that
> > I have to use metric, then all I have have to worry about are the
> > relationships between SI prefixes. Are there some tradeoffs that can be
> > made to simplify things?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/martinisgroup/pylabrad/issues/76#issuecomment-82750101>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martinisgroup/pylabrad/issues/76#issuecomment-82767349>
> .
>



-- 
Josh Mutus

**Comment by ejeffrey** [comment]
Closing since this seems to be just a discussion without an obvious resolution.
